### ISSUE TITLE
why not use fastcgi to connect php-fpm ?

### ISSUE THREAD

**Issue by jet6666** [paragi/sphp#7]
php-cgi maybe is not a good chioce .

**Comment by paragi** [comment]
Thank you for taking time to write me.
I think php-fpm would be the right solution, if you can fix the parameter transfer. (node session, websocket, preload etc) 
I haven't had the time to find a good solution. Do you have a suggestion?

**Comment by jet6666** [comment]
Thanks . I'm  finding the  php-fpm solutions .

1.node-fpm  :  [node-fpm](https://github.com/LastLeaf/node-fpm)
2.node-fastcgi-client  : [link](https://github.com/LastLeaf/node-fastcgi-client)

and https://github.com/longbill/node-phpfpm

I just trying checking which one can fulfill my requirement:
multriprocessing  socket server ,use  node as middleware and backend use php

**Comment by paragi** [comment]
Hi Jet

The target of SPHP is to serve PHP in embedded system with the following options:
- Websocket service on the same port as the express web service
- Transference of the express-session data to PHP
- Fastest possible response time under minimal load. 

These are attributes you would like for your fridge, more than for your public website :)
It would be nice to be able to serve both needs in one package!

From the manual: "FPM (FastCGI Process Manager) is an alternative PHP FastCGI implementation with some additional features (mostly) useful for heavy-loaded sites"

The features of this package is not trivial to do with fast-cgi, since you have little control over the superglobals in PHP. It is however a task I would like to attend to, when time permits. 

If you have any good insights as how to implement it, it would be appreciated.

If you intent to run a normal website (not embedded) you would probably prefer to optimise for good performance under heavy load. This package does not do that. 
If you don't need websockets on same port as the HTTP server or don't want to transfer node express session to PHP, you are better of with a basic fast-cgi solution.  It's uncomplicated and there are node packages that do just that.

I look forward to your input on the matter.
